### ISSUE TITLE
Wonsik Jeong hw

### ISSUE THREAD

**Issue by onesick** [ga-wdi-exercises/grumblr_angular#25]
https://github.com/onesick/grumblr_angular/tree/ui-router

Did not have time to work on CRUD. It's already 1:30AM. I will go to sleep and work on it ASAP when I have time tomorrow.
Comfortableness 3/5
stability? 2/5. Kinda iffy about the stuffs we learnt today. Need to review and practice

**Comment by jsm13** [comment]
:+1:
