### ISSUE TITLE
Chase's hw

### ISSUE THREAD

**Issue by cpgruber** [ga-wdi-exercises/grumblr_angular#28]
https://github.com/cpgruber/grumblr_angular/tree/cpgruber-solution

Comfort_level: 3
Completeness: 4

I really need to dig into angular more before upping comfort to a 4. I felt good adding crud after Monday, but yesterday threw me a little

**Comment by jshawl** [comment]
:+1: looks great! https://github.com/cpgruber/grumblr_angular/commit/1524b8cfe41786bedfa8e3fde338bbc76c4362d1
