### ISSUE TITLE
UI HW

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/grumblr_angular#30]
https://github.com/thomhouseholder/grumblr_angular/tree/ui-router

comfort level - 3.5
completeness - 5

Angular gets more interesting every lesson.  The concepts come along more naturally to me than some of the other stuff we've worked on.

**Comment by jshawl** [comment]
:+1: Excellent job on this assignment! a few inline comments on your commits - https://github.com/thomhouseholder/grumblr_angular/commits/ui-router
