### ISSUE TITLE
Eric Stennett - Angular_Grumbler Homework Wednesday

### ISSUE THREAD

**Issue by estennett** [ga-wdi-exercises/grumblr_angular#39]
Finished up the lesson plan.  Used solution and previous Grumblr example to finish CRD functionality.  

Complete: 4
Comfort: 3

https://github.com/estennett/grumblr_angular/tree/ui-router

**Comment by nolds9** [comment]
:+1: Good job on this, CRUD here is a little different since we are 'faking' it by using hard-coded objects for our seed data, we'll get more practice we the real thing, using ngResource to connect to APIs this week. Let me know if you any specific questions or areas you want feedback.
