### ISSUE TITLE
joe-gz hw

### ISSUE THREAD

**Issue by joe-gz** [ga-wdi-exercises/grumblr_angular#6]
https://github.com/joe-gz/grumblr_angular

comfort: i thought 5, but i'm having a lot of weird issues with the server response.  I understand that I cannot go to http://localhost:8080/grumbles because it will throw an error, but if i make a change to the index.html, those changes are not pulling throguh.  I've had to restart the server like 6 times, and I'm not sure what's going on.

completeness: i think 5?

**Comment by ebirving** [comment]
:+1:

Yeah...I was running into that server issue, too. Have you disabled caching when DevTools is open? If that's still not fixing it, you may have to manually clear the cache. Go to Chrome > Clear Browsing Data, and just select "Cached images and files" for the past few hours...
