### ISSUE TITLE
Mike Mahony HW submission

### ISSUE THREAD

**Issue by michaelmahony** [ga-wdi-exercises/grumblr_angular#96]
In trying to push to my forked repo, I got a number of git errors saying that the tip of my current branch is behind the remote counterparts... Perhaps I cloned from the wrong branch to begin with?

I have created a separate repo for my submission:
https://github.com/michaelmahony/grumblr-angular

**Comment by superbuggy** [comment]
thanks for creating separate repo. you may cloned rather than forked-- verify with `git remote -v` in terminal 👍
